export interface Airport {
  code: string;
  city: string;
  name: string;
  country: string;
}

export const AIRPORTS: Airport[] = [
  // ── India ──────────────────────────────────────────────────────────────────
  { code: "BOM", city: "Mumbai",              name: "Chhatrapati Shivaji Maharaj Intl",  country: "India" },
  { code: "DEL", city: "Delhi",               name: "Indira Gandhi International",        country: "India" },
  { code: "BLR", city: "Bengaluru",           name: "Kempegowda International",           country: "India" },
  { code: "MAA", city: "Chennai",             name: "Chennai International",              country: "India" },
  { code: "GOI", city: "Goa",                 name: "Dabolim Airport",                    country: "India" },
  { code: "HYD", city: "Hyderabad",           name: "Rajiv Gandhi International",         country: "India" },
  { code: "CCU", city: "Kolkata",             name: "Netaji Subhash Chandra Bose Intl",   country: "India" },
  { code: "PNQ", city: "Pune",                name: "Pune International",                 country: "India" },
  { code: "AMD", city: "Ahmedabad",           name: "Sardar Vallabhbhai Patel Intl",      country: "India" },
  { code: "JAI", city: "Jaipur",              name: "Jaipur International",               country: "India" },
  { code: "COK", city: "Kochi",               name: "Cochin International",               country: "India" },
  { code: "TRV", city: "Thiruvananthapuram",  name: "Trivandrum International",           country: "India" },
  { code: "IXC", city: "Chandigarh",          name: "Chandigarh International",           country: "India" },
  { code: "LKO", city: "Lucknow",             name: "Chaudhary Charan Singh Intl",        country: "India" },
  { code: "VNS", city: "Varanasi",            name: "Lal Bahadur Shastri International",  country: "India" },
  { code: "PAT", city: "Patna",               name: "Jay Prakash Narayan International",  country: "India" },
  { code: "GAU", city: "Guwahati",            name: "Lokpriya Gopinath Bordoloi Intl",    country: "India" },
  { code: "IXB", city: "Bagdogra",            name: "Bagdogra Airport",                   country: "India" },
  { code: "BBI", city: "Bhubaneswar",         name: "Biju Patnaik International",         country: "India" },
  { code: "VTZ", city: "Visakhapatnam",       name: "Visakhapatnam Airport",              country: "India" },
  { code: "IXM", city: "Madurai",             name: "Madurai Airport",                    country: "India" },
  { code: "CJB", city: "Coimbatore",          name: "Coimbatore International",           country: "India" },
  { code: "TRZ", city: "Tiruchirappalli",     name: "Tiruchirappalli International",      country: "India" },
  { code: "IXE", city: "Mangaluru",           name: "Mangaluru International",            country: "India" },
  { code: "IXZ", city: "Port Blair",          name: "Veer Savarkar International",        country: "India" },
  { code: "IXL", city: "Leh",                 name: "Kushok Bakula Rimpochee Airport",    country: "India" },
  { code: "SXR", city: "Srinagar",            name: "Sheikh ul-Alam International",       country: "India" },
  { code: "IXJ", city: "Jammu",               name: "Jammu Airport",                      country: "India" },
  { code: "ATQ", city: "Amritsar",            name: "Sri Guru Ram Dass Jee Intl",         country: "India" },
  { code: "DED", city: "Dehradun",            name: "Jolly Grant Airport",                country: "India" },
  { code: "IXD", city: "Prayagraj",           name: "Prayagraj Airport",                  country: "India" },
  { code: "VGA", city: "Vijayawada",          name: "Vijayawada International",           country: "India" },
  { code: "TIR", city: "Tirupati",            name: "Tirupati Airport",                   country: "India" },
  { code: "NAG", city: "Nagpur",              name: "Dr. Babasaheb Ambedkar Intl",        country: "India" },
  { code: "BHO", city: "Bhopal",              name: "Raja Bhoj Airport",                  country: "India" },
  { code: "IDR", city: "Indore",              name: "Devi Ahilyabai Holkar Airport",      country: "India" },
  { code: "JLR", city: "Jabalpur",            name: "Dumna Airport",                      country: "India" },
  { code: "BDQ", city: "Vadodara",            name: "Vadodara Airport",                   country: "India" },
  { code: "STV", city: "Surat",               name: "Surat Airport",                      country: "India" },
  { code: "RAJ", city: "Rajkot",              name: "Rajkot International",               country: "India" },
  { code: "JGA", city: "Jamnagar",            name: "Jamnagar Airport",                   country: "India" },
  { code: "UDR", city: "Udaipur",             name: "Maharana Pratap Airport",            country: "India" },
  { code: "JDH", city: "Jodhpur",             name: "Jodhpur Airport",                    country: "India" },
  { code: "IXA", city: "Agartala",            name: "Maharaja Bir Bikram Airport",        country: "India" },
  { code: "IMF", city: "Imphal",              name: "Bir Tikendrajit International",      country: "India" },
  { code: "DIB", city: "Dibrugarh",           name: "Dibrugarh Airport",                  country: "India" },
  { code: "IXS", city: "Silchar",             name: "Silchar Airport",                    country: "India" },
  { code: "TEZ", city: "Tezpur",              name: "Tezpur Airport",                     country: "India" },
  { code: "GOP", city: "Gorakhpur",           name: "Gorakhpur Airport",                  country: "India" },
  { code: "SAG", city: "Shirdi",              name: "Shirdi Airport",                     country: "India" },
  { code: "RJA", city: "Rajahmundry",         name: "Rajahmundry Airport",                country: "India" },
  { code: "PGH", city: "Pantnagar",           name: "Pantnagar Airport",                  country: "India" },
  { code: "KNU", city: "Kanpur",              name: "Kanpur Airport",                     country: "India" },
  { code: "AGX", city: "Agatti",              name: "Agatti Aerodrome",                   country: "India" },
  { code: "KTU", city: "Kota",                name: "Kota Airport",                       country: "India" },
  { code: "JSA", city: "Jaisalmer",           name: "Jaisalmer Airport",                  country: "India" },
  // ── Southeast Asia ─────────────────────────────────────────────────────────
  { code: "SIN", city: "Singapore",           name: "Changi Airport",                     country: "Singapore" },
  { code: "KUL", city: "Kuala Lumpur",        name: "Kuala Lumpur Intl (KLIA)",           country: "Malaysia" },
  { code: "BKK", city: "Bangkok",             name: "Suvarnabhumi Airport",               country: "Thailand" },
  { code: "DMK", city: "Bangkok",             name: "Don Mueang International",           country: "Thailand" },
  { code: "CNX", city: "Chiang Mai",          name: "Chiang Mai International",           country: "Thailand" },
  { code: "HKT", city: "Phuket",              name: "Phuket International",               country: "Thailand" },
  { code: "KBV", city: "Krabi",               name: "Krabi International",                country: "Thailand" },
  { code: "USM", city: "Koh Samui",           name: "Samui Airport",                      country: "Thailand" },
  { code: "HDY", city: "Hat Yai",             name: "Hat Yai International",              country: "Thailand" },
  { code: "UTH", city: "Udon Thani",          name: "Udon Thani International",           country: "Thailand" },
  { code: "CEI", city: "Chiang Rai",          name: "Mae Fah Luang International",        country: "Thailand" },
  { code: "PEN", city: "Penang",              name: "Penang International",               country: "Malaysia" },
  { code: "LGK", city: "Langkawi",            name: "Langkawi International",             country: "Malaysia" },
  { code: "BKI", city: "Kota Kinabalu",       name: "Kota Kinabalu International",        country: "Malaysia" },
  { code: "KCH", city: "Kuching",             name: "Kuching International",              country: "Malaysia" },
  { code: "JHB", city: "Johor Bahru",         name: "Senai International",                country: "Malaysia" },
  { code: "MYY", city: "Miri",                name: "Miri Airport",                       country: "Malaysia" },
  { code: "CGK", city: "Jakarta",             name: "Soekarno-Hatta International",       country: "Indonesia" },
  { code: "DPS", city: "Bali",                name: "Ngurah Rai International",           country: "Indonesia" },
  { code: "SUB", city: "Surabaya",            name: "Juanda International",               country: "Indonesia" },
  { code: "UPG", city: "Makassar",            name: "Sultan Hasanuddin International",    country: "Indonesia" },
  { code: "BPN", city: "Balikpapan",          name: "Sultan Aji Muhammad Sulaiman Intl",  country: "Indonesia" },
  { code: "JOG", city: "Yogyakarta",          name: "Adisutjipto International",          country: "Indonesia" },
  { code: "PLM", city: "Palembang",           name: "Sultan Mahmud Badaruddin II Intl",   country: "Indonesia" },
  { code: "SRG", city: "Semarang",            name: "Ahmad Yani International",           country: "Indonesia" },
  { code: "PKU", city: "Pekanbaru",           name: "Sultan Syarif Kasim II Intl",        country: "Indonesia" },
  { code: "MDC", city: "Manado",              name: "Sam Ratulangi International",        country: "Indonesia" },
  { code: "PNK", city: "Pontianak",           name: "Supadio International",              country: "Indonesia" },
  { code: "MNL", city: "Manila",              name: "Ninoy Aquino International",         country: "Philippines" },
  { code: "CEB", city: "Cebu",                name: "Mactan-Cebu International",          country: "Philippines" },
  { code: "DVO", city: "Davao",               name: "Francisco Bangoy International",     country: "Philippines" },
  { code: "ILO", city: "Iloilo",              name: "Iloilo International",               country: "Philippines" },
  { code: "CRK", city: "Clark",               name: "Clark International",                country: "Philippines" },
  { code: "SGN", city: "Ho Chi Minh City",    name: "Tan Son Nhat International",         country: "Vietnam" },
  { code: "HAN", city: "Hanoi",               name: "Noi Bai International",              country: "Vietnam" },
  { code: "DAD", city: "Da Nang",             name: "Da Nang International",              country: "Vietnam" },
  { code: "PQC", city: "Phu Quoc",            name: "Phu Quoc International",             country: "Vietnam" },
  { code: "RGN", city: "Yangon",              name: "Yangon International",               country: "Myanmar" },
  { code: "MDL", city: "Mandalay",            name: "Mandalay International",             country: "Myanmar" },
  { code: "VTE", city: "Vientiane",           name: "Wattay International",               country: "Laos" },
  { code: "PNH", city: "Phnom Penh",          name: "Phnom Penh International",           country: "Cambodia" },
  { code: "REP", city: "Siem Reap",           name: "Siem Reap International",            country: "Cambodia" },
  { code: "BWN", city: "Bandar Seri Begawan", name: "Brunei International",               country: "Brunei" },
  // ── Middle East ────────────────────────────────────────────────────────────
  { code: "DXB", city: "Dubai",               name: "Dubai International",                country: "UAE" },
  { code: "AUH", city: "Abu Dhabi",           name: "Zayed International",                country: "UAE" },
  { code: "DWC", city: "Dubai",               name: "Al Maktoum International",           country: "UAE" },
  { code: "SHJ", city: "Sharjah",             name: "Sharjah International",              country: "UAE" },
  { code: "DOH", city: "Doha",                name: "Hamad International",                country: "Qatar" },
  { code: "KWI", city: "Kuwait City",         name: "Kuwait International",               country: "Kuwait" },
  { code: "BAH", city: "Bahrain",             name: "Bahrain International",              country: "Bahrain" },
  { code: "RUH", city: "Riyadh",              name: "King Khalid International",          country: "Saudi Arabia" },
  { code: "JED", city: "Jeddah",              name: "King Abdulaziz International",       country: "Saudi Arabia" },
  { code: "MED", city: "Madinah",             name: "Prince Mohammad Bin Abdulaziz Intl", country: "Saudi Arabia" },
  { code: "DMM", city: "Dammam",              name: "King Fahd International",            country: "Saudi Arabia" },
  { code: "AHB", city: "Abha",                name: "Abha Regional Airport",              country: "Saudi Arabia" },
  { code: "MCT", city: "Muscat",              name: "Muscat International",               country: "Oman" },
  { code: "SLL", city: "Salalah",             name: "Salalah Airport",                    country: "Oman" },
  { code: "AMM", city: "Amman",               name: "Queen Alia International",           country: "Jordan" },
  { code: "BEY", city: "Beirut",              name: "Rafic Hariri International",         country: "Lebanon" },
  { code: "TLV", city: "Tel Aviv",            name: "Ben Gurion International",           country: "Israel" },
  { code: "BGW", city: "Baghdad",             name: "Baghdad International",              country: "Iraq" },
  { code: "BSR", city: "Basra",               name: "Basra International",                country: "Iraq" },
  { code: "EBL", city: "Erbil",               name: "Erbil International",                country: "Iraq" },
  { code: "DAM", city: "Damascus",            name: "Damascus International",             country: "Syria" },
  { code: "CAI", city: "Cairo",               name: "Cairo International",                country: "Egypt" },
  { code: "SSH", city: "Sharm el-Sheikh",     name: "Sharm el-Sheikh International",      country: "Egypt" },
  { code: "HRG", city: "Hurghada",            name: "Hurghada International",             country: "Egypt" },
  { code: "LXR", city: "Luxor",               name: "Luxor International",                country: "Egypt" },
  { code: "ASW", city: "Aswan",               name: "Aswan International",                country: "Egypt" },
  // ── Turkey ─────────────────────────────────────────────────────────────────
  { code: "IST", city: "Istanbul",            name: "Istanbul Airport",                   country: "Turkey" },
  { code: "SAW", city: "Istanbul",            name: "Sabiha Gökçen International",        country: "Turkey" },
  { code: "AYT", city: "Antalya",             name: "Antalya Airport",                    country: "Turkey" },
  { code: "ADB", city: "Izmir",               name: "Adnan Menderes International",       country: "Turkey" },
  { code: "ESB", city: "Ankara",              name: "Esenboga International",             country: "Turkey" },
  { code: "ADA", city: "Adana",               name: "Adana Şakirpaşa Airport",            country: "Turkey" },
  { code: "BJV", city: "Bodrum",              name: "Milas–Bodrum Airport",               country: "Turkey" },
  { code: "DLM", city: "Dalaman",             name: "Dalaman Airport",                    country: "Turkey" },
  { code: "GZT", city: "Gaziantep",           name: "Oğuzeli International",              country: "Turkey" },
  { code: "TZX", city: "Trabzon",             name: "Trabzon Airport",                    country: "Turkey" },
  // ── Central & South Asia ───────────────────────────────────────────────────
  { code: "KHI", city: "Karachi",             name: "Jinnah International",               country: "Pakistan" },
  { code: "LHE", city: "Lahore",              name: "Allama Iqbal International",         country: "Pakistan" },
  { code: "ISB", city: "Islamabad",           name: "New Islamabad International",        country: "Pakistan" },
  { code: "PEW", city: "Peshawar",            name: "Bacha Khan International",           country: "Pakistan" },
  { code: "MUX", city: "Multan",              name: "Multan International",               country: "Pakistan" },
  { code: "SKT", city: "Sialkot",             name: "Sialkot International",              country: "Pakistan" },
  { code: "LYP", city: "Faisalabad",          name: "Faisalabad International",           country: "Pakistan" },
  { code: "DAC", city: "Dhaka",               name: "Hazrat Shahjalal International",     country: "Bangladesh" },
  { code: "CGP", city: "Chittagong",          name: "Shah Amanat International",          country: "Bangladesh" },
  { code: "ZYL", city: "Sylhet",              name: "Osmani International",               country: "Bangladesh" },
  { code: "CMB", city: "Colombo",             name: "Bandaranaike International",         country: "Sri Lanka" },
  { code: "HRI", city: "Hambantota",          name: "Mattala Rajapaksa International",    country: "Sri Lanka" },
  { code: "KTM", city: "Kathmandu",           name: "Tribhuvan International",            country: "Nepal" },
  { code: "PKR", city: "Pokhara",             name: "Pokhara Regional Airport",           country: "Nepal" },
  { code: "PBH", city: "Paro",                name: "Paro Airport",                       country: "Bhutan" },
  { code: "MLE", city: "Malé",                name: "Velana International",               country: "Maldives" },
  { code: "GAN", city: "Addu City",           name: "Gan Airport",                        country: "Maldives" },
  { code: "TAS", city: "Tashkent",            name: "Islam Karimov International",        country: "Uzbekistan" },
  { code: "SKD", city: "Samarkand",           name: "Samarkand Airport",                  country: "Uzbekistan" },
  { code: "BHK", city: "Bukhara",             name: "Bukhara Airport",                    country: "Uzbekistan" },
  { code: "FRU", city: "Bishkek",             name: "Manas International",                country: "Kyrgyzstan" },
  { code: "ALA", city: "Almaty",              name: "Almaty International",               country: "Kazakhstan" },
  { code: "NQZ", city: "Astana",              name: "Nursultan Nazarbayev Intl",          country: "Kazakhstan" },
  { code: "DYU", city: "Dushanbe",            name: "Dushanbe International",             country: "Tajikistan" },
  { code: "ASB", city: "Ashgabat",            name: "Ashgabat International",             country: "Turkmenistan" },
  { code: "GYD", city: "Baku",                name: "Heydar Aliyev International",        country: "Azerbaijan" },
  { code: "TBS", city: "Tbilisi",             name: "Tbilisi International",              country: "Georgia" },
  { code: "BUS", city: "Batumi",              name: "Batumi International",               country: "Georgia" },
  { code: "EVN", city: "Yerevan",             name: "Zvartnots International",            country: "Armenia" },
  { code: "KBL", city: "Kabul",               name: "Hamid Karzai International",         country: "Afghanistan" },
  // ── East Asia ──────────────────────────────────────────────────────────────
  { code: "PEK", city: "Beijing",             name: "Capital International",              country: "China" },
  { code: "PKX", city: "Beijing",             name: "Daxing International",               country: "China" },
  { code: "PVG", city: "Shanghai",            name: "Pudong International",               country: "China" },
  { code: "SHA", city: "Shanghai",            name: "Hongqiao International",             country: "China" },
  { code: "CAN", city: "Guangzhou",           name: "Baiyun International",               country: "China" },
  { code: "SZX", city: "Shenzhen",            name: "Bao'an International",               country: "China" },
  { code: "CTU", city: "Chengdu",             name: "Tianfu International",               country: "China" },
  { code: "KMG", city: "Kunming",             name: "Changshui International",            country: "China" },
  { code: "XIY", city: "Xi'an",               name: "Xianyang International",             country: "China" },
  { code: "WUH", city: "Wuhan",               name: "Tianhe International",               country: "China" },
  { code: "CGO", city: "Zhengzhou",           name: "Xinzheng International",             country: "China" },
  { code: "NKG", city: "Nanjing",             name: "Lukou International",                country: "China" },
  { code: "HGH", city: "Hangzhou",            name: "Xiaoshan International",             country: "China" },
  { code: "XMN", city: "Xiamen",              name: "Gaoqi International",                country: "China" },
  { code: "CKG", city: "Chongqing",           name: "Jiangbei International",             country: "China" },
  { code: "TAO", city: "Qingdao",             name: "Jiaodong International",             country: "China" },
  { code: "DLC", city: "Dalian",              name: "Zhoushuizi International",           country: "China" },
  { code: "SHE", city: "Shenyang",            name: "Taoxian International",              country: "China" },
  { code: "HRB", city: "Harbin",              name: "Taiping International",              country: "China" },
  { code: "CGQ", city: "Changchun",           name: "Longjia International",              country: "China" },
  { code: "HAK", city: "Haikou",              name: "Meilan International",               country: "China" },
  { code: "SYX", city: "Sanya",               name: "Phoenix International",              country: "China" },
  { code: "NNG", city: "Nanning",             name: "Wuxu International",                 country: "China" },
  { code: "KWL", city: "Guilin",              name: "Liangjiang International",           country: "China" },
  { code: "FOC", city: "Fuzhou",              name: "Changle International",              country: "China" },
  { code: "URC", city: "Urumqi",              name: "Diwopu International",               country: "China" },
  { code: "LHW", city: "Lanzhou",             name: "Zhongchuan International",           country: "China" },
  { code: "TSN", city: "Tianjin",             name: "Binhai International",               country: "China" },
  { code: "HKG", city: "Hong Kong",           name: "Hong Kong International",            country: "Hong Kong" },
  { code: "MFM", city: "Macau",               name: "Macau International",                country: "Macau" },
  { code: "TPE", city: "Taipei",              name: "Taiwan Taoyuan International",       country: "Taiwan" },
  { code: "TSA", city: "Taipei",              name: "Taipei Songshan Airport",            country: "Taiwan" },
  { code: "KHH", city: "Kaohsiung",           name: "Kaohsiung International",            country: "Taiwan" },
  { code: "ICN", city: "Seoul",               name: "Incheon International",              country: "South Korea" },
  { code: "GMP", city: "Seoul",               name: "Gimpo International",                country: "South Korea" },
  { code: "PUS", city: "Busan",               name: "Gimhae International",               country: "South Korea" },
  { code: "CJU", city: "Jeju",                name: "Jeju International",                 country: "South Korea" },
  { code: "TAE", city: "Daegu",               name: "Daegu International",                country: "South Korea" },
  { code: "NRT", city: "Tokyo",               name: "Narita International",               country: "Japan" },
  { code: "HND", city: "Tokyo",               name: "Haneda Airport",                     country: "Japan" },
  { code: "KIX", city: "Osaka",               name: "Kansai International",               country: "Japan" },
  { code: "ITM", city: "Osaka",               name: "Itami Airport",                      country: "Japan" },
  { code: "CTS", city: "Sapporo",             name: "New Chitose Airport",                country: "Japan" },
  { code: "OKA", city: "Okinawa",             name: "Naha Airport",                       country: "Japan" },
  { code: "FUK", city: "Fukuoka",             name: "Fukuoka Airport",                    country: "Japan" },
  { code: "NGO", city: "Nagoya",              name: "Chubu Centrair International",       country: "Japan" },
  { code: "HIJ", city: "Hiroshima",           name: "Hiroshima Airport",                  country: "Japan" },
  { code: "KMJ", city: "Kumamoto",            name: "Kumamoto Airport",                   country: "Japan" },
  { code: "KOJ", city: "Kagoshima",           name: "Kagoshima Airport",                  country: "Japan" },
  { code: "OIT", city: "Oita",                name: "Oita Airport",                       country: "Japan" },
  { code: "ULN", city: "Ulaanbaatar",         name: "Chinggis Khaan International",       country: "Mongolia" },
  // ── Europe – UK & Ireland ──────────────────────────────────────────────────
  { code: "LHR", city: "London",              name: "Heathrow Airport",                   country: "UK" },
  { code: "LGW", city: "London",              name: "Gatwick Airport",                    country: "UK" },
  { code: "STN", city: "London",              name: "Stansted Airport",                   country: "UK" },
  { code: "LTN", city: "London",              name: "Luton Airport",                      country: "UK" },
  { code: "LCY", city: "London",              name: "London City Airport",                country: "UK" },
  { code: "MAN", city: "Manchester",          name: "Manchester Airport",                 country: "UK" },
  { code: "BHX", city: "Birmingham",          name: "Birmingham Airport",                 country: "UK" },
  { code: "EDI", city: "Edinburgh",           name: "Edinburgh Airport",                  country: "UK" },
  { code: "GLA", city: "Glasgow",             name: "Glasgow International",              country: "UK" },
  { code: "BRS", city: "Bristol",             name: "Bristol Airport",                    country: "UK" },
  { code: "NCL", city: "Newcastle",           name: "Newcastle International",            country: "UK" },
  { code: "LBA", city: "Leeds",               name: "Leeds Bradford Airport",             country: "UK" },
  { code: "BFS", city: "Belfast",             name: "George Best Belfast City Airport",   country: "UK" },
  { code: "DUB", city: "Dublin",              name: "Dublin Airport",                     country: "Ireland" },
  { code: "SNN", city: "Shannon",             name: "Shannon Airport",                    country: "Ireland" },
  { code: "ORK", city: "Cork",                name: "Cork Airport",                       country: "Ireland" },
  // ── Europe – Western ───────────────────────────────────────────────────────
  { code: "CDG", city: "Paris",               name: "Charles de Gaulle Airport",          country: "France" },
  { code: "ORY", city: "Paris",               name: "Orly Airport",                       country: "France" },
  { code: "NCE", city: "Nice",                name: "Nice Côte d'Azur Airport",           country: "France" },
  { code: "LYS", city: "Lyon",                name: "Saint-Exupéry Airport",              country: "France" },
  { code: "MRS", city: "Marseille",           name: "Marseille Provence Airport",         country: "France" },
  { code: "TLS", city: "Toulouse",            name: "Toulouse Blagnac Airport",           country: "France" },
  { code: "BOD", city: "Bordeaux",            name: "Bordeaux–Mérignac Airport",          country: "France" },
  { code: "NTE", city: "Nantes",              name: "Nantes Atlantique Airport",          country: "France" },
  { code: "SXB", city: "Strasbourg",          name: "Strasbourg Airport",                 country: "France" },
  { code: "AMS", city: "Amsterdam",           name: "Schiphol Airport",                   country: "Netherlands" },
  { code: "RTM", city: "Rotterdam",           name: "Rotterdam The Hague Airport",        country: "Netherlands" },
  { code: "EIN", city: "Eindhoven",           name: "Eindhoven Airport",                  country: "Netherlands" },
  { code: "BRU", city: "Brussels",            name: "Brussels Airport",                   country: "Belgium" },
  { code: "CRL", city: "Brussels",            name: "Brussels South Charleroi Airport",   country: "Belgium" },
  { code: "LUX", city: "Luxembourg",          name: "Luxembourg Airport",                 country: "Luxembourg" },
  { code: "FRA", city: "Frankfurt",           name: "Frankfurt Airport",                  country: "Germany" },
  { code: "MUC", city: "Munich",              name: "Munich Airport",                     country: "Germany" },
  { code: "BER", city: "Berlin",              name: "Brandenburg Airport",                country: "Germany" },
  { code: "HAM", city: "Hamburg",             name: "Hamburg Airport",                    country: "Germany" },
  { code: "DUS", city: "Düsseldorf",          name: "Düsseldorf Airport",                 country: "Germany" },
  { code: "CGN", city: "Cologne",             name: "Cologne Bonn Airport",               country: "Germany" },
  { code: "STR", city: "Stuttgart",           name: "Stuttgart Airport",                  country: "Germany" },
  { code: "NUE", city: "Nuremberg",           name: "Nuremberg Airport",                  country: "Germany" },
  { code: "ZRH", city: "Zurich",              name: "Zurich Airport",                     country: "Switzerland" },
  { code: "GVA", city: "Geneva",              name: "Geneva Airport",                     country: "Switzerland" },
  { code: "BSL", city: "Basel",               name: "EuroAirport Basel Mulhouse Freiburg", country: "Switzerland" },
  { code: "VIE", city: "Vienna",              name: "Vienna International",               country: "Austria" },
  { code: "SZG", city: "Salzburg",            name: "Salzburg Airport",                   country: "Austria" },
  { code: "GRZ", city: "Graz",                name: "Graz Airport",                       country: "Austria" },
  { code: "INN", city: "Innsbruck",           name: "Innsbruck Airport",                  country: "Austria" },
  // ── Europe – Iberia ────────────────────────────────────────────────────────
  { code: "MAD", city: "Madrid",              name: "Adolfo Suárez Madrid–Barajas",       country: "Spain" },
  { code: "BCN", city: "Barcelona",           name: "Josep Tarradellas Barcelona–El Prat", country: "Spain" },
  { code: "PMI", city: "Palma de Mallorca",   name: "Palma de Mallorca Airport",          country: "Spain" },
  { code: "VLC", city: "Valencia",            name: "Valencia Airport",                   country: "Spain" },
  { code: "AGP", city: "Málaga",              name: "Málaga–Costa del Sol Airport",       country: "Spain" },
  { code: "SVQ", city: "Seville",             name: "Seville Airport",                    country: "Spain" },
  { code: "BIO", city: "Bilbao",              name: "Bilbao Airport",                     country: "Spain" },
  { code: "TFS", city: "Tenerife",            name: "Tenerife South Airport",             country: "Spain" },
  { code: "LPA", city: "Gran Canaria",        name: "Gran Canaria Airport",               country: "Spain" },
  { code: "FUE", city: "Fuerteventura",       name: "Fuerteventura Airport",              country: "Spain" },
  { code: "ACE", city: "Lanzarote",           name: "Lanzarote Airport",                  country: "Spain" },
  { code: "ALC", city: "Alicante",            name: "Alicante–Elche Airport",             country: "Spain" },
  { code: "GRX", city: "Granada",             name: "Federico García Lorca Airport",      country: "Spain" },
  { code: "LIS", city: "Lisbon",              name: "Humberto Delgado Airport",           country: "Portugal" },
  { code: "OPO", city: "Porto",               name: "Francisco de Sá Carneiro Airport",  country: "Portugal" },
  { code: "FAO", city: "Faro",                name: "Faro Airport",                       country: "Portugal" },
  { code: "FNC", city: "Funchal",             name: "Madeira Airport",                    country: "Portugal" },
  { code: "PDL", city: "Ponta Delgada",       name: "João Paulo II Airport",              country: "Portugal" },
  // ── Europe – Italy ─────────────────────────────────────────────────────────
  { code: "FCO", city: "Rome",                name: "Leonardo da Vinci–Fiumicino",        country: "Italy" },
  { code: "CIA", city: "Rome",                name: "Ciampino Airport",                   country: "Italy" },
  { code: "MXP", city: "Milan",               name: "Malpensa Airport",                   country: "Italy" },
  { code: "LIN", city: "Milan",               name: "Linate Airport",                     country: "Italy" },
  { code: "BGY", city: "Milan",               name: "Orio al Serio Airport",              country: "Italy" },
  { code: "VCE", city: "Venice",              name: "Marco Polo Airport",                 country: "Italy" },
  { code: "FLR", city: "Florence",            name: "Peretola Airport",                   country: "Italy" },
  { code: "NAP", city: "Naples",              name: "Naples International",               country: "Italy" },
  { code: "BRI", city: "Bari",                name: "Karol Wojtyła Airport",              country: "Italy" },
  { code: "CTA", city: "Catania",             name: "Catania-Fontanarossa Airport",       country: "Italy" },
  { code: "PMO", city: "Palermo",             name: "Falcone–Borsellino Airport",         country: "Italy" },
  { code: "PSA", city: "Pisa",                name: "Galileo Galilei Airport",            country: "Italy" },
  { code: "BOL", city: "Bologna",             name: "Guglielmo Marconi Airport",          country: "Italy" },
  { code: "TRN", city: "Turin",               name: "Turin Airport",                      country: "Italy" },
  // ── Europe – Greece ────────────────────────────────────────────────────────
  { code: "ATH", city: "Athens",              name: "Eleftherios Venizelos International", country: "Greece" },
  { code: "SKG", city: "Thessaloniki",        name: "Macedonia Airport",                  country: "Greece" },
  { code: "HER", city: "Heraklion",           name: "Nikos Kazantzakis Airport",          country: "Greece" },
  { code: "RHO", city: "Rhodes",              name: "Diagoras Airport",                   country: "Greece" },
  { code: "CHQ", city: "Chania",              name: "Daskalogiannis Airport",             country: "Greece" },
  { code: "CFU", city: "Corfu",               name: "Ioannis Kapodistrias Airport",       country: "Greece" },
  { code: "JMK", city: "Mykonos",             name: "Mykonos Airport",                    country: "Greece" },
  { code: "JTR", city: "Santorini",           name: "Santorini Airport",                  country: "Greece" },
  { code: "ZTH", city: "Zakynthos",           name: "Dionysios Solomos Airport",          country: "Greece" },
  { code: "KGS", city: "Kos",                 name: "Kos Island International",           country: "Greece" },
  // ── Europe – Scandinavia ───────────────────────────────────────────────────
  { code: "OSL", city: "Oslo",                name: "Oslo Gardermoen Airport",            country: "Norway" },
  { code: "BGO", city: "Bergen",              name: "Bergen Airport, Flesland",           country: "Norway" },
  { code: "SVG", city: "Stavanger",           name: "Stavanger Airport, Sola",            country: "Norway" },
  { code: "TOS", city: "Tromsø",              name: "Tromsø Airport",                     country: "Norway" },
  { code: "ARN", city: "Stockholm",           name: "Stockholm Arlanda Airport",          country: "Sweden" },
  { code: "GOT", city: "Gothenburg",          name: "Gothenburg Landvetter Airport",      country: "Sweden" },
  { code: "MMX", city: "Malmö",               name: "Malmö Airport",                      country: "Sweden" },
  { code: "CPH", city: "Copenhagen",          name: "Copenhagen Airport",                 country: "Denmark" },
  { code: "BLL", city: "Billund",             name: "Billund Airport",                    country: "Denmark" },
  { code: "AAL", city: "Aalborg",             name: "Aalborg Airport",                    country: "Denmark" },
  { code: "HEL", city: "Helsinki",            name: "Helsinki Airport",                   country: "Finland" },
  { code: "OUL", city: "Oulu",                name: "Oulu Airport",                       country: "Finland" },
  { code: "TMP", city: "Tampere",             name: "Tampere–Pirkkala Airport",           country: "Finland" },
  { code: "RVN", city: "Rovaniemi",           name: "Rovaniemi Airport",                  country: "Finland" },
  // ── Europe – Eastern & Baltic ──────────────────────────────────────────────
  { code: "WAW", city: "Warsaw",              name: "Chopin Airport",                     country: "Poland" },
  { code: "KRK", city: "Kraków",              name: "John Paul II International",         country: "Poland" },
  { code: "GDN", city: "Gdańsk",              name: "Lech Wałęsa Airport",                country: "Poland" },
  { code: "WRO", city: "Wrocław",             name: "Copernicus Airport",                 country: "Poland" },
  { code: "KTW", city: "Katowice",            name: "Katowice International",             country: "Poland" },
  { code: "PRG", city: "Prague",              name: "Václav Havel Airport",               country: "Czech Republic" },
  { code: "BTS", city: "Bratislava",          name: "M. R. Štefánik Airport",             country: "Slovakia" },
  { code: "BUD", city: "Budapest",            name: "Budapest Ferenc Liszt International", country: "Hungary" },
  { code: "DEB", city: "Debrecen",            name: "Debrecen International",             country: "Hungary" },
  { code: "OTP", city: "Bucharest",           name: "Henri Coandă International",         country: "Romania" },
  { code: "CLJ", city: "Cluj-Napoca",         name: "Cluj-Napoca International",          country: "Romania" },
  { code: "SOF", city: "Sofia",               name: "Sofia Airport",                      country: "Bulgaria" },
  { code: "VAR", city: "Varna",               name: "Varna Airport",                      country: "Bulgaria" },
  { code: "BOJ", city: "Burgas",              name: "Burgas Airport",                     country: "Bulgaria" },
  { code: "TLL", city: "Tallinn",             name: "Lennart Meri Tallinn Airport",       country: "Estonia" },
  { code: "RIX", city: "Riga",                name: "Riga International",                 country: "Latvia" },
  { code: "VNO", city: "Vilnius",             name: "Vilnius Airport",                    country: "Lithuania" },
  { code: "ZAG", city: "Zagreb",              name: "Franjo Tuđman Airport",              country: "Croatia" },
  { code: "SPU", city: "Split",               name: "Split Airport",                      country: "Croatia" },
  { code: "DBV", city: "Dubrovnik",           name: "Dubrovnik Airport",                  country: "Croatia" },
  { code: "BEG", city: "Belgrade",            name: "Nikola Tesla Airport",               country: "Serbia" },
  { code: "SKP", city: "Skopje",              name: "Alexander the Great Airport",        country: "North Macedonia" },
  { code: "TGD", city: "Podgorica",           name: "Podgorica Airport",                  country: "Montenegro" },
  { code: "TIV", city: "Tivat",               name: "Tivat Airport",                      country: "Montenegro" },
  { code: "LJU", city: "Ljubljana",           name: "Jože Pučnik Airport",                country: "Slovenia" },
  { code: "SJJ", city: "Sarajevo",            name: "Sarajevo International",             country: "Bosnia" },
  { code: "TIA", city: "Tirana",              name: "Mother Teresa Airport",              country: "Albania" },
  { code: "PRN", city: "Pristina",            name: "Pristina International",             country: "Kosovo" },
  { code: "MSQ", city: "Minsk",               name: "Minsk National Airport",             country: "Belarus" },
  { code: "KBP", city: "Kyiv",                name: "Boryspil International",             country: "Ukraine" },
  { code: "LWO", city: "Lviv",                name: "Danylo Halytskyi International",     country: "Ukraine" },
  { code: "ODS", city: "Odesa",               name: "Odesa International",                country: "Ukraine" },
  { code: "SVO", city: "Moscow",              name: "Sheremetyevo International",         country: "Russia" },
  { code: "DME", city: "Moscow",              name: "Domodedovo International",           country: "Russia" },
  { code: "VKO", city: "Moscow",              name: "Vnukovo International",              country: "Russia" },
  { code: "LED", city: "St. Petersburg",      name: "Pulkovo Airport",                    country: "Russia" },
  { code: "SVX", city: "Yekaterinburg",       name: "Koltsovo Airport",                   country: "Russia" },
  { code: "OVB", city: "Novosibirsk",         name: "Tolmachevo Airport",                 country: "Russia" },
  { code: "KZN", city: "Kazan",               name: "Kazan International",                country: "Russia" },
  { code: "AER", city: "Sochi",               name: "Sochi Airport",                      country: "Russia" },
  { code: "KHV", city: "Khabarovsk",          name: "Khabarovsk Novy Airport",            country: "Russia" },
  { code: "VVO", city: "Vladivostok",         name: "Vladivostok International",          country: "Russia" },
  { code: "IKT", city: "Irkutsk",             name: "Irkutsk Airport",                    country: "Russia" },
  // ── Africa – North ─────────────────────────────────────────────────────────
  { code: "ALG", city: "Algiers",             name: "Houari Boumediene Airport",          country: "Algeria" },
  { code: "ORN", city: "Oran",                name: "Ahmed Ben Bella Airport",            country: "Algeria" },
  { code: "TUN", city: "Tunis",               name: "Tunis-Carthage Airport",             country: "Tunisia" },
  { code: "CMN", city: "Casablanca",          name: "Mohammed V International",           country: "Morocco" },
  { code: "RAK", city: "Marrakech",           name: "Marrakech Menara Airport",           country: "Morocco" },
  { code: "AGA", city: "Agadir",              name: "Al Massira Airport",                 country: "Morocco" },
  { code: "TNG", city: "Tangier",             name: "Ibn Batouta Airport",                country: "Morocco" },
  { code: "FEZ", city: "Fez",                 name: "Fès–Saïss Airport",                  country: "Morocco" },
  { code: "TIP", city: "Tripoli",             name: "Mitiga Airport",                     country: "Libya" },
  { code: "KRT", city: "Khartoum",            name: "Khartoum International",             country: "Sudan" },
  // ── Africa – West ──────────────────────────────────────────────────────────
  { code: "DKR", city: "Dakar",               name: "Blaise Diagne International",        country: "Senegal" },
  { code: "ABJ", city: "Abidjan",             name: "Félix-Houphouët-Boigny Intl",        country: "Côte d'Ivoire" },
  { code: "ACC", city: "Accra",               name: "Kotoka International",               country: "Ghana" },
  { code: "LOS", city: "Lagos",               name: "Murtala Muhammed International",     country: "Nigeria" },
  { code: "ABV", city: "Abuja",               name: "Nnamdi Azikiwe International",       country: "Nigeria" },
  { code: "KAN", city: "Kano",                name: "Mallam Aminu Kano International",    country: "Nigeria" },
  { code: "PHC", city: "Port Harcourt",       name: "Port Harcourt International",        country: "Nigeria" },
  { code: "BKO", city: "Bamako",              name: "Modibo Keïta International",         country: "Mali" },
  { code: "OUA", city: "Ouagadougou",         name: "Thomas Sankara International",       country: "Burkina Faso" },
  { code: "NIM", city: "Niamey",              name: "Diori Hamani International",         country: "Niger" },
  { code: "CKY", city: "Conakry",             name: "Conakry International",              country: "Guinea" },
  { code: "FNA", city: "Freetown",            name: "Lungi International",                country: "Sierra Leone" },
  { code: "ROB", city: "Monrovia",            name: "Roberts International",              country: "Liberia" },
  { code: "OXB", city: "Bissau",              name: "Osvaldo Vieira International",       country: "Guinea-Bissau" },
  { code: "BJL", city: "Banjul",              name: "Banjul International",               country: "Gambia" },
  { code: "NDJ", city: "N'Djamena",           name: "Hassan Djamous International",       country: "Chad" },
  // ── Africa – Central ───────────────────────────────────────────────────────
  { code: "DLA", city: "Douala",              name: "Douala International",               country: "Cameroon" },
  { code: "NSI", city: "Yaoundé",             name: "Yaoundé Nsimalen International",     country: "Cameroon" },
  { code: "SSG", city: "Malabo",              name: "Santa Isabel Airport",               country: "Equatorial Guinea" },
  { code: "LBV", city: "Libreville",          name: "Léon-Mba International",             country: "Gabon" },
  { code: "BZV", city: "Brazzaville",         name: "Maya-Maya Airport",                  country: "Congo" },
  { code: "PNR", city: "Pointe-Noire",        name: "Agostinho-Neto Airport",             country: "Congo" },
  { code: "FIH", city: "Kinshasa",            name: "N'Djili Airport",                    country: "DRC" },
  { code: "FBM", city: "Lubumbashi",          name: "Lubumbashi International",           country: "DRC" },
  { code: "BGF", city: "Bangui",              name: "Bangui M'Poko International",        country: "CAR" },
  { code: "LAD", city: "Luanda",              name: "Quatro de Fevereiro Airport",        country: "Angola" },
  // ── Africa – East ──────────────────────────────────────────────────────────
  { code: "ADD", city: "Addis Ababa",         name: "Bole International",                 country: "Ethiopia" },
  { code: "DJI", city: "Djibouti",            name: "Ambouli International",              country: "Djibouti" },
  { code: "ASM", city: "Asmara",              name: "Asmara International",               country: "Eritrea" },
  { code: "HGA", city: "Hargeisa",            name: "Egal International",                 country: "Somaliland" },
  { code: "MGQ", city: "Mogadishu",           name: "Aden Adde International",            country: "Somalia" },
  { code: "NBO", city: "Nairobi",             name: "Jomo Kenyatta International",        country: "Kenya" },
  { code: "MBA", city: "Mombasa",             name: "Moi International",                  country: "Kenya" },
  { code: "EBB", city: "Entebbe",             name: "Entebbe International",              country: "Uganda" },
  { code: "KGL", city: "Kigali",              name: "Kigali International",               country: "Rwanda" },
  { code: "BJM", city: "Bujumbura",           name: "Bujumbura International",            country: "Burundi" },
  { code: "DAR", city: "Dar es Salaam",       name: "Julius Nyerere International",       country: "Tanzania" },
  { code: "ZNZ", city: "Zanzibar",            name: "Abeid Amani Karume International",   country: "Tanzania" },
  { code: "MWZ", city: "Mwanza",              name: "Mwanza Airport",                     country: "Tanzania" },
  // ── Africa – Southern ──────────────────────────────────────────────────────
  { code: "JNB", city: "Johannesburg",        name: "O.R. Tambo International",           country: "South Africa" },
  { code: "CPT", city: "Cape Town",           name: "Cape Town International",            country: "South Africa" },
  { code: "DUR", city: "Durban",              name: "King Shaka International",           country: "South Africa" },
  { code: "PLZ", city: "Port Elizabeth",      name: "Chief Dawid Stuurman Intl",          country: "South Africa" },
  { code: "GRJ", city: "George",              name: "George Airport",                     country: "South Africa" },
  { code: "BFN", city: "Bloemfontein",        name: "Bram Fischer International",         country: "South Africa" },
  { code: "MQP", city: "Nelspruit",           name: "Kruger Mpumalanga International",    country: "South Africa" },
  { code: "HRE", city: "Harare",              name: "Robert Gabriel Mugabe Intl",         country: "Zimbabwe" },
  { code: "BUQ", city: "Bulawayo",            name: "Joshua Mqabuko Nkomo Intl",          country: "Zimbabwe" },
  { code: "VFA", city: "Victoria Falls",      name: "Victoria Falls Airport",             country: "Zimbabwe" },
  { code: "LUN", city: "Lusaka",              name: "Kenneth Kaunda International",       country: "Zambia" },
  { code: "WDH", city: "Windhoek",            name: "Hosea Kutako International",         country: "Namibia" },
  { code: "GBE", city: "Gaborone",            name: "Sir Seretse Khama International",    country: "Botswana" },
  { code: "MPM", city: "Maputo",              name: "Maputo International",               country: "Mozambique" },
  { code: "BEW", city: "Beira",               name: "Beira Airport",                      country: "Mozambique" },
  { code: "TNR", city: "Antananarivo",        name: "Ivato International",                country: "Madagascar" },
  { code: "MRU", city: "Mauritius",           name: "Sir Seewoosagur Ramgoolam Intl",     country: "Mauritius" },
  { code: "RUN", city: "Réunion",             name: "Roland Garros Airport",              country: "Réunion" },
  { code: "SEZ", city: "Seychelles",          name: "Seychelles International",           country: "Seychelles" },
  // ── North America – USA ────────────────────────────────────────────────────
  { code: "JFK", city: "New York",            name: "John F. Kennedy International",      country: "USA" },
  { code: "LGA", city: "New York",            name: "LaGuardia Airport",                  country: "USA" },
  { code: "EWR", city: "Newark",              name: "Newark Liberty International",       country: "USA" },
  { code: "BOS", city: "Boston",              name: "Logan International",                country: "USA" },
  { code: "PHL", city: "Philadelphia",        name: "Philadelphia International",         country: "USA" },
  { code: "DCA", city: "Washington DC",       name: "Reagan National Airport",            country: "USA" },
  { code: "IAD", city: "Washington DC",       name: "Dulles International",               country: "USA" },
  { code: "BWI", city: "Baltimore",           name: "BWI Marshall Airport",               country: "USA" },
  { code: "ATL", city: "Atlanta",             name: "Hartsfield–Jackson Atlanta Intl",    country: "USA" },
  { code: "MIA", city: "Miami",               name: "Miami International",                country: "USA" },
  { code: "FLL", city: "Fort Lauderdale",     name: "Fort Lauderdale–Hollywood Intl",     country: "USA" },
  { code: "MCO", city: "Orlando",             name: "Orlando International",              country: "USA" },
  { code: "TPA", city: "Tampa",               name: "Tampa International",                country: "USA" },
  { code: "JAX", city: "Jacksonville",        name: "Jacksonville International",         country: "USA" },
  { code: "RSW", city: "Fort Myers",          name: "Southwest Florida International",    country: "USA" },
  { code: "CLT", city: "Charlotte",           name: "Charlotte Douglas International",    country: "USA" },
  { code: "RDU", city: "Raleigh",             name: "Raleigh–Durham International",       country: "USA" },
  { code: "BNA", city: "Nashville",           name: "Nashville International",            country: "USA" },
  { code: "MEM", city: "Memphis",             name: "Memphis International",              country: "USA" },
  { code: "MSY", city: "New Orleans",         name: "Louis Armstrong International",      country: "USA" },
  { code: "ORD", city: "Chicago",             name: "O'Hare International",               country: "USA" },
  { code: "MDW", city: "Chicago",             name: "Midway International",               country: "USA" },
  { code: "DTW", city: "Detroit",             name: "Detroit Metropolitan Airport",       country: "USA" },
  { code: "CLE", city: "Cleveland",           name: "Cleveland Hopkins International",    country: "USA" },
  { code: "PIT", city: "Pittsburgh",          name: "Pittsburgh International",           country: "USA" },
  { code: "CMH", city: "Columbus",            name: "John Glenn Columbus International",  country: "USA" },
  { code: "IND", city: "Indianapolis",        name: "Indianapolis International",         country: "USA" },
  { code: "MKE", city: "Milwaukee",           name: "Mitchell International",             country: "USA" },
  { code: "MSP", city: "Minneapolis",         name: "Minneapolis–Saint Paul Intl",        country: "USA" },
  { code: "STL", city: "St. Louis",           name: "St. Louis Lambert International",    country: "USA" },
  { code: "MCI", city: "Kansas City",         name: "Kansas City International",          country: "USA" },
  { code: "OMA", city: "Omaha",               name: "Eppley Airfield",                    country: "USA" },
  { code: "DEN", city: "Denver",              name: "Denver International",               country: "USA" },
  { code: "SLC", city: "Salt Lake City",      name: "Salt Lake City International",       country: "USA" },
  { code: "PHX", city: "Phoenix",             name: "Phoenix Sky Harbor International",   country: "USA" },
  { code: "TUS", city: "Tucson",              name: "Tucson International",               country: "USA" },
  { code: "ABQ", city: "Albuquerque",         name: "Albuquerque International Sunport",  country: "USA" },
  { code: "ELP", city: "El Paso",             name: "El Paso International",              country: "USA" },
  { code: "SAT", city: "San Antonio",         name: "San Antonio International",          country: "USA" },
  { code: "AUS", city: "Austin",              name: "Austin-Bergstrom International",     country: "USA" },
  { code: "DFW", city: "Dallas",              name: "Dallas/Fort Worth International",    country: "USA" },
  { code: "DAL", city: "Dallas",              name: "Dallas Love Field",                  country: "USA" },
  { code: "IAH", city: "Houston",             name: "George Bush Intercontinental",       country: "USA" },
  { code: "HOU", city: "Houston",             name: "William P. Hobby Airport",           country: "USA" },
  { code: "LAX", city: "Los Angeles",         name: "Los Angeles International",          country: "USA" },
  { code: "SFO", city: "San Francisco",       name: "San Francisco International",        country: "USA" },
  { code: "SJC", city: "San Jose",            name: "Norman Y. Mineta San José Intl",     country: "USA" },
  { code: "OAK", city: "Oakland",             name: "Oakland International",              country: "USA" },
  { code: "SMF", city: "Sacramento",          name: "Sacramento International",           country: "USA" },
  { code: "SAN", city: "San Diego",           name: "San Diego International",            country: "USA" },
  { code: "LAS", city: "Las Vegas",           name: "Harry Reid International",           country: "USA" },
  { code: "RNO", city: "Reno",                name: "Reno–Tahoe International",           country: "USA" },
  { code: "PDX", city: "Portland",            name: "Portland International",             country: "USA" },
  { code: "SEA", city: "Seattle",             name: "Seattle–Tacoma International",       country: "USA" },
  { code: "ANC", city: "Anchorage",           name: "Ted Stevens Anchorage Intl",         country: "USA" },
  { code: "HNL", city: "Honolulu",            name: "Daniel K. Inouye International",     country: "USA" },
  { code: "OGG", city: "Maui",                name: "Kahului Airport",                    country: "USA" },
  { code: "KOA", city: "Kona",                name: "Ellison Onizuka Kona International", country: "USA" },
  { code: "LIH", city: "Kauai",               name: "Lihue Airport",                      country: "USA" },
  { code: "OKC", city: "Oklahoma City",       name: "Will Rogers World Airport",          country: "USA" },
  { code: "TUL", city: "Tulsa",               name: "Tulsa International",                country: "USA" },
  { code: "BHM", city: "Birmingham",          name: "Birmingham–Shuttlesworth Intl",      country: "USA" },
  { code: "BUF", city: "Buffalo",             name: "Buffalo Niagara International",      country: "USA" },
  { code: "SYR", city: "Syracuse",            name: "Syracuse Hancock International",     country: "USA" },
  { code: "ALB", city: "Albany",              name: "Albany International",               country: "USA" },
  { code: "RIC", city: "Richmond",            name: "Richmond International",             country: "USA" },
  { code: "ORF", city: "Norfolk",             name: "Norfolk International",              country: "USA" },
  { code: "MHT", city: "Manchester",          name: "Manchester–Boston Regional",         country: "USA" },
  { code: "PWM", city: "Portland ME",         name: "Portland International Jetport",     country: "USA" },
  { code: "BTV", city: "Burlington",          name: "Burlington International",           country: "USA" },
  { code: "GRR", city: "Grand Rapids",        name: "Gerald R. Ford International",       country: "USA" },
  { code: "DSM", city: "Des Moines",          name: "Des Moines International",           country: "USA" },
  { code: "BZN", city: "Bozeman",             name: "Bozeman Yellowstone International",  country: "USA" },
  { code: "GEG", city: "Spokane",             name: "Spokane International",              country: "USA" },
  { code: "BOI", city: "Boise",               name: "Boise Airport",                      country: "USA" },
  { code: "FAI", city: "Fairbanks",           name: "Fairbanks International",            country: "USA" },
  { code: "JNU", city: "Juneau",              name: "Juneau International",               country: "USA" },
  // ── North America – Canada ─────────────────────────────────────────────────
  { code: "YYZ", city: "Toronto",             name: "Toronto Pearson International",      country: "Canada" },
  { code: "YTZ", city: "Toronto",             name: "Billy Bishop Toronto City Airport",  country: "Canada" },
  { code: "YUL", city: "Montreal",            name: "Montréal–Trudeau International",     country: "Canada" },
  { code: "YVR", city: "Vancouver",           name: "Vancouver International",            country: "Canada" },
  { code: "YYC", city: "Calgary",             name: "Calgary International",              country: "Canada" },
  { code: "YEG", city: "Edmonton",            name: "Edmonton International",             country: "Canada" },
  { code: "YWG", city: "Winnipeg",            name: "Winnipeg James Armstrong Richardson", country: "Canada" },
  { code: "YQB", city: "Quebec City",         name: "Jean Lesage International",          country: "Canada" },
  { code: "YHZ", city: "Halifax",             name: "Halifax Stanfield International",    country: "Canada" },
  { code: "YYT", city: "St. John's",          name: "St. John's International",           country: "Canada" },
  { code: "YZF", city: "Yellowknife",         name: "Yellowknife Airport",                country: "Canada" },
  { code: "YXE", city: "Saskatoon",           name: "Saskatoon John G. Diefenbaker Intl", country: "Canada" },
  { code: "YQR", city: "Regina",              name: "Regina International",               country: "Canada" },
  { code: "YYJ", city: "Victoria",            name: "Victoria International",             country: "Canada" },
  { code: "YOW", city: "Ottawa",              name: "Ottawa Macdonald–Cartier Intl",      country: "Canada" },
  // ── Mexico ─────────────────────────────────────────────────────────────────
  { code: "MEX", city: "Mexico City",         name: "Benito Juárez International",        country: "Mexico" },
  { code: "CUN", city: "Cancún",              name: "Cancún International",               country: "Mexico" },
  { code: "GDL", city: "Guadalajara",         name: "Miguel Hidalgo y Costilla Intl",     country: "Mexico" },
  { code: "MTY", city: "Monterrey",           name: "General Mariano Escobedo Intl",      country: "Mexico" },
  { code: "SJD", city: "Los Cabos",           name: "Los Cabos International",            country: "Mexico" },
  { code: "PVR", city: "Puerto Vallarta",     name: "Licenciado Gustavo Díaz Ordaz Intl", country: "Mexico" },
  { code: "MZT", city: "Mazatlán",            name: "General Rafael Buelna International", country: "Mexico" },
  { code: "ZIH", city: "Ixtapa-Zihuatanejo",  name: "Ixtapa-Zihuatanejo International",   country: "Mexico" },
  { code: "HUX", city: "Huatulco",            name: "Bahías de Huatulco International",   country: "Mexico" },
  { code: "OAX", city: "Oaxaca",              name: "Xoxocotlán International",           country: "Mexico" },
  { code: "TIJ", city: "Tijuana",             name: "General Abelardo L. Rodríguez Intl", country: "Mexico" },
  { code: "HMO", city: "Hermosillo",          name: "General Ignacio Pesqueira García",   country: "Mexico" },
  { code: "MID", city: "Mérida",              name: "Manuel Crescencio Rejón International", country: "Mexico" },
  { code: "CUL", city: "Culiacán",            name: "Federal de Bachigualato International", country: "Mexico" },
  { code: "VER", city: "Veracruz",            name: "General Heriberto Jara International", country: "Mexico" },
  { code: "TAP", city: "Tapachula",           name: "Tapachula International",            country: "Mexico" },
  // ── Caribbean & Central America ────────────────────────────────────────────
  { code: "PTY", city: "Panama City",         name: "Tocumen International",              country: "Panama" },
  { code: "SJO", city: "San José",            name: "Juan Santamaría International",      country: "Costa Rica" },
  { code: "LIR", city: "Liberia",             name: "Daniel Oduber Quirós International", country: "Costa Rica" },
  { code: "SAP", city: "San Pedro Sula",      name: "Ramón Villeda Morales International", country: "Honduras" },
  { code: "TGU", city: "Tegucigalpa",         name: "Toncontín International",            country: "Honduras" },
  { code: "MGA", city: "Managua",             name: "Augusto C. Sandino International",   country: "Nicaragua" },
  { code: "GUA", city: "Guatemala City",      name: "La Aurora International",            country: "Guatemala" },
  { code: "SAL", city: "San Salvador",        name: "El Salvador International",          country: "El Salvador" },
  { code: "SDQ", city: "Santo Domingo",       name: "Las Américas International",         country: "Dominican Republic" },
  { code: "PUJ", city: "Punta Cana",          name: "Punta Cana International",           country: "Dominican Republic" },
  { code: "HAV", city: "Havana",              name: "José Martí International",           country: "Cuba" },
  { code: "KIN", city: "Kingston",            name: "Norman Manley International",        country: "Jamaica" },
  { code: "MBJ", city: "Montego Bay",         name: "Sangster International",             country: "Jamaica" },
  { code: "NAS", city: "Nassau",              name: "Lynden Pindling International",      country: "Bahamas" },
  { code: "PLS", city: "Providenciales",      name: "Providenciales International",       country: "Turks & Caicos" },
  { code: "AUA", city: "Aruba",               name: "Queen Beatrix International",        country: "Aruba" },
  { code: "CUR", city: "Curaçao",             name: "Hato International",                 country: "Curaçao" },
  { code: "BGI", city: "Barbados",            name: "Grantley Adams International",       country: "Barbados" },
  { code: "POS", city: "Port of Spain",       name: "Piarco International",               country: "Trinidad & Tobago" },
  { code: "SXM", city: "St. Maarten",         name: "Princess Juliana International",     country: "St. Maarten" },
  { code: "ANU", city: "Antigua",             name: "V.C. Bird International",            country: "Antigua & Barbuda" },
  { code: "GND", city: "Grenada",             name: "Maurice Bishop International",       country: "Grenada" },
  { code: "SVD", city: "St. Vincent",         name: "Argyle International",               country: "St. Vincent" },
  { code: "SLU", city: "St. Lucia",           name: "Hewanorra International",            country: "St. Lucia" },
  { code: "STT", city: "St. Thomas",          name: "Cyril E. King Airport",              country: "USVI" },
  // ── South America ──────────────────────────────────────────────────────────
  { code: "GRU", city: "São Paulo",           name: "Guarulhos International",            country: "Brazil" },
  { code: "CGH", city: "São Paulo",           name: "Congonhas Airport",                  country: "Brazil" },
  { code: "VCP", city: "Campinas",            name: "Viracopos International",            country: "Brazil" },
  { code: "GIG", city: "Rio de Janeiro",      name: "Galeão International",               country: "Brazil" },
  { code: "SDU", city: "Rio de Janeiro",      name: "Santos Dumont Airport",              country: "Brazil" },
  { code: "BSB", city: "Brasília",            name: "Presidente Juscelino Kubitschek Intl", country: "Brazil" },
  { code: "SSA", city: "Salvador",            name: "Deputado Luís Eduardo Magalhães Intl", country: "Brazil" },
  { code: "FOR", city: "Fortaleza",           name: "Pinto Martins International",        country: "Brazil" },
  { code: "REC", city: "Recife",              name: "Guararapes–Gilberto Freyre Intl",    country: "Brazil" },
  { code: "BEL", city: "Belém",               name: "Val de Cans International",          country: "Brazil" },
  { code: "MAO", city: "Manaus",              name: "Eduardo Gomes International",        country: "Brazil" },
  { code: "CWB", city: "Curitiba",            name: "Afonso Pena International",          country: "Brazil" },
  { code: "POA", city: "Porto Alegre",        name: "Salgado Filho International",        country: "Brazil" },
  { code: "FLN", city: "Florianópolis",       name: "Hercílio Luz International",         country: "Brazil" },
  { code: "NAT", city: "Natal",               name: "Governador Aluízio Alves Intl",      country: "Brazil" },
  { code: "MCZ", city: "Maceió",              name: "Zumbi dos Palmares International",   country: "Brazil" },
  { code: "CGB", city: "Cuiabá",              name: "Marechal Rondon International",      country: "Brazil" },
  { code: "CGR", city: "Campo Grande",        name: "Campo Grande International",         country: "Brazil" },
  { code: "SLZ", city: "São Luís",            name: "Marechal Cunha Machado Intl",        country: "Brazil" },
  { code: "EZE", city: "Buenos Aires",        name: "Ministro Pistarini International",   country: "Argentina" },
  { code: "AEP", city: "Buenos Aires",        name: "Jorge Newbery Airfield",             country: "Argentina" },
  { code: "COR", city: "Córdoba",             name: "Ingeniero Aeronáutico Ambrosio LVT", country: "Argentina" },
  { code: "MDZ", city: "Mendoza",             name: "El Plumerillo International",        country: "Argentina" },
  { code: "BRC", city: "Bariloche",           name: "Teniente Luis Candelaria Airport",   country: "Argentina" },
  { code: "ROS", city: "Rosario",             name: "Islas Malvinas International",       country: "Argentina" },
  { code: "IGR", city: "Puerto Iguazú",       name: "Cataratas del Iguazú International", country: "Argentina" },
  { code: "SCL", city: "Santiago",            name: "Arturo Merino Benítez International", country: "Chile" },
  { code: "PMC", city: "Puerto Montt",        name: "El Tepual Airport",                  country: "Chile" },
  { code: "PUQ", city: "Punta Arenas",        name: "Presidente Carlos Ibáñez del Campo", country: "Chile" },
  { code: "ANF", city: "Antofagasta",         name: "Andrés Sabella Gálvez International", country: "Chile" },
  { code: "IQQ", city: "Iquique",             name: "Diego Aracena International",        country: "Chile" },
  { code: "LIM", city: "Lima",                name: "Jorge Chávez International",         country: "Peru" },
  { code: "CUZ", city: "Cusco",               name: "Alejandro Velasco Astete Intl",      country: "Peru" },
  { code: "AQP", city: "Arequipa",            name: "Rodríguez Ballón International",     country: "Peru" },
  { code: "IQT", city: "Iquitos",             name: "Coronel FAP Francisco Secada Intl",  country: "Peru" },
  { code: "BOG", city: "Bogotá",              name: "El Dorado International",            country: "Colombia" },
  { code: "MDE", city: "Medellín",            name: "José María Córdova International",   country: "Colombia" },
  { code: "CLO", city: "Cali",                name: "Alfonso Bonilla Aragón International", country: "Colombia" },
  { code: "CTG", city: "Cartagena",           name: "Rafael Núñez International",         country: "Colombia" },
  { code: "BAQ", city: "Barranquilla",        name: "Ernesto Cortissoz International",    country: "Colombia" },
  { code: "ADZ", city: "San Andrés",          name: "Gustavo Rojas Pinilla International", country: "Colombia" },
  { code: "MVD", city: "Montevideo",          name: "Carrasco International",             country: "Uruguay" },
  { code: "UIO", city: "Quito",               name: "Mariscal Sucre International",       country: "Ecuador" },
  { code: "GYE", city: "Guayaquil",           name: "José Joaquín de Olmedo International", country: "Ecuador" },
  { code: "CUE", city: "Cuenca",              name: "Mariscal Lamar Airport",             country: "Ecuador" },
  { code: "LPB", city: "La Paz",              name: "El Alto International",              country: "Bolivia" },
  { code: "VVI", city: "Santa Cruz",          name: "Viru Viru International",            country: "Bolivia" },
  { code: "CBB", city: "Cochabamba",          name: "Jorge Wilstermann International",    country: "Bolivia" },
  { code: "ASU", city: "Asunción",            name: "Silvio Pettirossi International",    country: "Paraguay" },
  { code: "CCS", city: "Caracas",             name: "Simón Bolívar International",        country: "Venezuela" },
  { code: "MAR", city: "Maracaibo",           name: "La Chinita International",           country: "Venezuela" },
  { code: "GEO", city: "Georgetown",          name: "Cheddi Jagan International",         country: "Guyana" },
  { code: "PBM", city: "Paramaribo",          name: "Johan Adolf Pengel International",   country: "Suriname" },
  // ── Oceania ────────────────────────────────────────────────────────────────
  { code: "SYD", city: "Sydney",              name: "Kingsford Smith Airport",            country: "Australia" },
  { code: "MEL", city: "Melbourne",           name: "Melbourne Airport",                  country: "Australia" },
  { code: "BNE", city: "Brisbane",            name: "Brisbane Airport",                   country: "Australia" },
  { code: "PER", city: "Perth",               name: "Perth Airport",                      country: "Australia" },
  { code: "ADL", city: "Adelaide",            name: "Adelaide Airport",                   country: "Australia" },
  { code: "CBR", city: "Canberra",            name: "Canberra Airport",                   country: "Australia" },
  { code: "HBA", city: "Hobart",              name: "Hobart International",               country: "Australia" },
  { code: "DRW", city: "Darwin",              name: "Darwin International",               country: "Australia" },
  { code: "CNS", city: "Cairns",              name: "Cairns Airport",                     country: "Australia" },
  { code: "OOL", city: "Gold Coast",          name: "Gold Coast Airport",                 country: "Australia" },
  { code: "TSV", city: "Townsville",          name: "Townsville Airport",                 country: "Australia" },
  { code: "MKY", city: "Mackay",              name: "Mackay Airport",                     country: "Australia" },
  { code: "ROK", city: "Rockhampton",         name: "Rockhampton Airport",                country: "Australia" },
  { code: "NTL", city: "Newcastle",           name: "Newcastle Airport",                  country: "Australia" },
  { code: "ASP", city: "Alice Springs",       name: "Alice Springs Airport",              country: "Australia" },
  { code: "AYQ", city: "Uluru",               name: "Ayers Rock Airport",                 country: "Australia" },
  { code: "AKL", city: "Auckland",            name: "Auckland Airport",                   country: "New Zealand" },
  { code: "WLG", city: "Wellington",          name: "Wellington Airport",                 country: "New Zealand" },
  { code: "CHC", city: "Christchurch",        name: "Christchurch Airport",               country: "New Zealand" },
  { code: "ZQN", city: "Queenstown",          name: "Queenstown Airport",                 country: "New Zealand" },
  { code: "DUD", city: "Dunedin",             name: "Dunedin Airport",                    country: "New Zealand" },
  { code: "HLZ", city: "Hamilton",            name: "Hamilton Airport",                   country: "New Zealand" },
  { code: "NAN", city: "Nadi",                name: "Nadi International",                 country: "Fiji" },
  { code: "SUV", city: "Suva",                name: "Nausori International",              country: "Fiji" },
  { code: "RAR", city: "Rarotonga",           name: "Rarotonga International",            country: "Cook Islands" },
  { code: "PPT", city: "Papeete",             name: "Faa'a International",                country: "French Polynesia" },
  { code: "BOB", city: "Bora Bora",           name: "Motu Mute Airport",                  country: "French Polynesia" },
  { code: "APW", city: "Apia",                name: "Faleolo International",              country: "Samoa" },
  { code: "HIR", city: "Honiara",             name: "Honiara International",              country: "Solomon Islands" },
  { code: "POM", city: "Port Moresby",        name: "Jacksons International",             country: "Papua New Guinea" },
  { code: "VLI", city: "Port Vila",           name: "Bauerfield International",           country: "Vanuatu" },
  { code: "NOU", city: "Nouméa",              name: "La Tontouta International",          country: "New Caledonia" },
  { code: "GUM", city: "Guam",                name: "A.B. Won Pat International",         country: "Guam" },
  { code: "SPN", city: "Saipan",              name: "Francisco C. Ada Saipan Intl",       country: "CNMI" },
  { code: "PPG", city: "Pago Pago",           name: "Pago Pago International",            country: "American Samoa" },
  { code: "INU", city: "Nauru",               name: "Nauru International",                country: "Nauru" },
  { code: "FUN", city: "Funafuti",             name: "Funafuti International",             country: "Tuvalu" },
  { code: "TRW", city: "Tarawa",              name: "Bonriki International",              country: "Kiribati" },
];
