import { RoomType } from "@/context/BookingFlowContext";

export const MOCK_ROOMS: RoomType[] = [
  {
    id: "deluxe-king",
    name: "Deluxe King Room",
    description: "Spacious room with king bed, city views, marble bathroom with rain shower, and a cozy sitting area.",
    bedType: "1 King Bed",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "City View", "Rain Shower", "Mini Bar", "Safe"],
    pricePerNight: 189,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=75",
    available: true,
  },
  {
    id: "superior-twin",
    name: "Superior Twin Room",
    description: "Bright twin room with two queen beds, perfect for friends or families. Includes a work desk and lounge chair.",
    bedType: "2 Queen Beds",
    maxGuests: 4,
    amenities: ["Free Wi-Fi", "Garden View", "Bathtub", "Work Desk", "Safe"],
    pricePerNight: 219,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1590490360182-c33d955e4f64?w=600&q=75",
    available: true,
  },
  {
    id: "premium-suite",
    name: "Premium Suite",
    description: "Luxurious suite with separate living area, panoramic views, soaking tub, walk-in closet, and butler service.",
    bedType: "1 King Bed + Sofa Bed",
    maxGuests: 3,
    amenities: ["Free Wi-Fi", "Panoramic View", "Soaking Tub", "Butler Service", "Nespresso Machine", "Lounge Access"],
    pricePerNight: 429,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=75",
    available: true,
  },
  {
    id: "executive-studio",
    name: "Executive Studio",
    description: "Contemporary studio with kitchenette, ideal for extended stays. Features a queen bed and dedicated workspace.",
    bedType: "1 Queen Bed",
    maxGuests: 2,
    amenities: ["Free Wi-Fi", "Kitchenette", "Work Desk", "Washer/Dryer", "Smart TV"],
    pricePerNight: 259,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600&q=75",
    available: true,
  },
  {
    id: "family-connecting",
    name: "Family Connecting Rooms",
    description: "Two connecting rooms with a king bed and twin beds, ideal for families. Shared living space with kid-friendly amenities.",
    bedType: "1 King + 2 Twin Beds",
    maxGuests: 5,
    amenities: ["Free Wi-Fi", "Pool View", "Connecting Rooms", "Mini Fridge", "Game Console"],
    pricePerNight: 349,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=600&q=75",
    available: false,
  },
];

export const MOCK_HOTEL = {
  name: "The Grand Voyagr Hotel & Spa",
  image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=75",
  city: "Dubai, UAE",
  stars: 5,
};
